### ISSUE TITLE
Regression with 'speed-up, strict DNS parsing on lan packets' commit

### ISSUE THREAD

**Issue by glitsj16** [netblue30/fdns#10]
Hi, I played around some more today with fdns built from git master. I'm seeing loads of consecutive errors with https://github.com/netblue30/fdns/commit/4f5798b8776500ad3afebf1d0174bbe79b922dea:

```
(0) Error: rx local invalid header
(0) Error: PACKET DROPPED
```

Although DNS resolution is working, something seems to be off (the keep-alive is affected?). You can see logs from both fdns [with](https://gist.github.com/glitsj16/ef6b8e4e65dc41dd35974a7e828c55d5) and [without](https://gist.github.com/glitsj16/bbe6088596b975fc08d2915ce77a2995) the offending commit. For good measure I added a [log](https://gist.github.com/glitsj16/e9bb5d374ebb5d7a0f23ebaa7c2cd9c2) of fdns with the `--debug` flag for the latest git master code too. HTH.

Regards

**Comment by glitsj16** [comment]
**FOLLOW-UP**: on a whim I double-checked my `/etc/resolv.conf` and guess what, I had a few options in there that badly interfered with fdns (leftovers from earlier unbound/dnscrypt-proxy usage):

```
nameserver 127.0.0.1
options timeout:1 edns0 single-request single-request-reopen
```

As soon as I dropped the second line things started to flow as expected! The monitor now reports cached items as well, so I'll add a note to #4 as well soonish. Perhaps a note somewhere to not use these resolvconf params could help avoiding stuff like this. Apologies for the confusion, fdns feels snappy now!

Happy coding

**Comment by netblue30** [comment]
Sure, no problem.
