### ISSUE TITLE
Option to disable ipv6

### ISSUE THREAD

**Issue by glitsj16** [netblue30/fdns#13]
During prolonged use of `fdns --monitor` the stats view it offers gets polluted rather quickly when ipv6 is not enabled on your machine. It's filled with `(ipv6) dropped` entrees and the high rate of its dropped counter might confuse the user into thinking something is wrong. Would it be possible to have a knob to disable ipv6?

**Comment by netblue30** [comment]
I've noticed it, quite annoying. Let's try this: I'll disable all counts and monitor info for ipv6 (received, dropped, etc.) if ipv6 is disabled, and only enable all of them if the user specifically requests --ipv6.

**Comment by startx2017** [comment]
Closed for now!

**Comment by glitsj16** [comment]
> Let's try this: I'll disable all counts and monitor info for ipv6 (received, dropped, etc.) if ipv6 is disabled, and only enable all of them if the user specifically requests --ipv6.

Looks much better now, but I _still see a high count of dropped requests_ in the monitor. Just a FYI, as I'm used to it by now and I assume these are mostly dropped ipv6 requests. Wanted to bring this to the attention of @startx2017 too now he has taken over #13.

```
digital-society ENCRYPTED (SSL 16.30 ms, fallback 0), 
requests 128, drop 60, cache 16, fwd 0
...
```

**Comment by netblue30** [comment]
Yes, something wrong there, the count still goes up - it is probably an ipv6 count. I'll take a look.

**Comment by glitsj16** [comment]
Confirming https://github.com/glitsj16/fdns/commit/39df8bde1e87934c220a47c47c87093fdf4e06b7 fixed the high drop count. Looking really impressive now with new servers flowing in.

Cheers!
