### ISSUE TITLE
Functional state of the fdns.service

### ISSUE THREAD

**Issue by glitsj16** [netblue30/fdns#15]
After some very nice work by @rusty-snake the fdns systemd service unit got much improved hardening (see https://github.com/netblue30/fdns/commit/f3ec6691df5b44c214721f010572af4c024a778e, https://github.com/netblue30/fdns/commit/eb5cd4b441f4294ad41eceb831f65b52d1a2efb2, https://github.com/netblue30/fdns/commit/285de74c3ff541c3f424d46c047e04fe31f40c0f and https://github.com/netblue30/fdns/commit/4b3f545d15367a42949d81baec1e9e68108779fe). To ensure we can offer support for as many distro's as possible, I extensively tested fdns on both _Arch Linux_ and _Ubuntu 16.04 LTS_ over the last week. On the verge of 2020 the latter is indeed aging, but still officially supported and working very nicely (both as desktop and server). Specifically, testing these OS'es offered an opportunity to compare `older` (v229) versus `newer` (v244) versions of `systemd`. Below are my findings, perhaps this needs to be discussed somewhere and this is as good a place as any.

Let's start with the unit type. As common for daemons, `Type=forking` was preferred over _Type=simple_. After all fdns has this nice `--daemonize` switch, so why not use it? Although the forking type could be enhanced with additional _PIDFile=_ and possibly also _RemainAfterExit=yes_ stanzas (according to man systemd.service), I would like to suggest to go with `Type=simple` nonetheless. Testing showed this to be the more reliable option on both systems. Views may differ offcourse, and other opinions are very welcome. Just note that if we opt for simple we'll need to drop the _--daemonize_ in ExecStart= lines.

Another crucial part of the systemd hardening is the `ProtectSystem` option. As is, this is currently qualified as `strict`. I noticed two drawbacks in this context:
- occasionally causes '_can not create /run/fdns_' errors on Arch;
- is unsupported on older systemd versions (like Ubuntu 16.04 LTS).
Luckily there's a way around this. If we would instead go for something like...

```
ProtectSystem=full
ReadOnlyDirectories=/
ReadWriteDirectories=/run
```

... the observed drawbacks are alleviated without loosing (too) much on the hardening front IMHO. Do note that newer systemd uses ReadOnlyPaths/ReadWritePaths, but both dialects seem to be fully supported.

That's about it, ugh! @rusty-snake could perhaps come up with scores for these suggested changes, so we can have some sort of stick for measuring its impact :)

Enjoy the holidays

**Comment by rusty-snake** [comment]
@glitsj16 first thanks for so much testing. :1st_place_medal: 

`Type=simple` ~`--daemonize`~ sounds good to me.
  - systemd supports it and prefer it (Type=simple is the default).
  - We can simplify the log all queries block

---

```
ProtectSystem=full
ReadOnlyDirectories=/
ReadWriteDirectories=/run
```

fdns needs `/run/fdns` writeable, right? @netblue30 for what is it? It is an empty dir on my system.

@glitsj16 I'm currently hardening all my systemd services. I also written a custom unit to update my /etc/hosts, this is a bit tricky if you want `ProtectSystem=strict` (PSs). First I tried to simply using PSs and `ReadWritePaths=/etc/hosts` which does not work for files, only for directories. I ended up with "whitelisting" /etc/... this work rw even if PPs.
```
ProtectSystem=strict
TemporaryFileSystem=/etc
BindPaths=/etc/hosts
BindReadOnlyPaths=-/etc/crypto-policies
BindReadOnlyPaths=-/etc/pki
BindReadOnlyPaths=-/etc/nsswitch.conf
```

Systemd requires "whitelist" paths to be present (as firejail), to "whitelist" paths only if they are present and ignore these path silently otherwise, we prefix the path with `-`. But what to do if the program would create the path. Firejail has `mkdir` and `mkfile` for that. The systemd equivalents are `ExecStartPre=+/bin/mkdir` and `ExecStartPre=+/bin/touch`. The `+` prefix means with full privileges.

Solution:

1. Ignore it/fix it in fdns if `/run/fdns` is never used
2. create it and mount it rw
```
ProtectSystem=strict
# TODO: Permission of /run/fdns
ExecStartPre=+/bin/mkdir /run/fdns
ReadWritePaths=/run/fdns
```
3. create it, mount it rw and whitelist in /run
```
ProtectSystem=strict
ExecStartPre=+/bin/mkdir /run/fdns
BindPaths=/run/fdns
BindReadOnlyPaths=-/run/…
```

**Comment by glitsj16** [comment]
> fdns needs /run/fdns writeable, right?

@rusty-snake Correct. Let's wait for @netblue30's response to incorporate your additional hardening. In other words, I've seen your suggestions, look OK to me :+1: .

**Comment by rusty-snake** [comment]
@glitsj16 can your confirm that this works.
```
ProtectSystem=strict
RuntimeDirectory=fdns
ReadWritePaths=/run/fdns
```
IDK if the `ReadWritePaths` is necessary.

**Comment by rusty-snake** [comment]
I did one round strace, the following paths in /etc are also accessed, to you thing we need any of them?
```
ld.so.preload
ld.so.cache
system-fips
localtime
```

**Comment by glitsj16** [comment]
> @glitsj16 can your confirm that this works.
> 
> ProtectSystem=strict
> RuntimeDirectory=fdns
> ReadWritePaths=/run/fdns
> 

@rusty-snake For compatibility with older systemd versions that don't support the `strict` value, I'd suggest going for

```
# FJ: --read-only=/ (except: /dev, /proc /sys)
ProtectSystem=full
ReadOnlyDirectories=/
RuntimeDirectory=fdns
ReadWriteDirectories=/run/fdns
```

That seems to work just fine, nice find. Feel free to put that in.

> I did one round strace, the following paths in /etc are also accessed, to you thing we need any of them?
> 
> ld.so.preload
> ld.so.cache
> system-fips
> localtime
> 

I'm not sure we need those, but I didn't do any testing to speak of without them. I'm still having issues with `dig` cfr. https://github.com/netblue30/fdns/issues/4 that I'm trying to debug.

**Comment by rusty-snake** [comment]
@glitsj16 `ProtectSystem=full` conflicts with "private-etc".

**Comment by glitsj16** [comment]
> @glitsj16 ProtectSystem=full conflicts with "private-etc".

@rusty-snake Too bad, supporting older systemd versions was going too break sooner or later. I've lost count how many combinations I've been testing lately. Feel free to make the changes you need to get it in good working order. I'll be taking a few days off but will pick-up testing Ubuntu 16.04's older systemd again later on, and can always add notes if it needs something besides the defaults. Enjoy the holidays!

**Comment by rusty-snake** [comment]
`--proxy-addr=` is broken in the systemd-unit, but not if started on the command line. @glitsj16 do you use `--proxy-addr=` / is you Arch error with RestrictAddressFamilies something like "failed check address family in net.c" (can't find the error log).

**Comment by glitsj16** [comment]
@rusty-snake 

> --proxy-addr= is broken in the systemd-unit, but not if started on the command line

On Arch I have `ExecStart=/usr/bin/fdns --proxy-addr=127.0.0.1 --server=foo` and that is working fine. I'll check my Ubuntu 16.04 LTS machine later, that uses the exact same ExecStart=...

> is you Arch error with RestrictAddressFamilies something like "failed check address family in net.c" (can't find the error log).

I see this in /tmp/fdns.log when enabling `StandardOutput=append:/tmp/fdns.log`:

Error getifaddrs: net.c:54 net_check_proxy_addr: Address family not supported by protocol

**Comment by rusty-snake** [comment]
@glitsj16 I found it. `RestrictAddressFamilies` is not broken on Arch, it is broken if `--proxy-addr=` is used. We need to change the note.

BTW: Is `AF_INET6` in `RestrictAddressFamilies` required?
(#20; `grep "AF_INET6" src/fdns/*.c` = nothing)

**Comment by glitsj16** [comment]
> RestrictAddressFamilies is not broken on Arch, it is broken if --proxy-addr= is used.

@rusty-snake Confirmed. `--proxy-addr-any` does work.

**Comment by glitsj16** [comment]
UPDATE: added (crude) `ExecStopPost` command to remove the stats file after stopping the service (as [suggested in #14 here](https://github.com/netblue30/fdns/issues/14#issuecomment-570940958)).
