### ISSUE TITLE
libseccomp error

### ISSUE THREAD

**Issue by luckypoem** [netblue30/fdns#22]
hi.

on my mac.
git clone https://github.com/netblue30/fdns
cd fdns
./configure --prefix=/usr
it shows:
...
checking for main in -lseccomp... no
configure: error: *** libseccomp not installed ***
yudeMacBook-Air:fdns brite$ brew install libseccomp
Updating Homebrew...
^C
Error: No available formula with the name "libseccomp" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
yudeMacBook-Air:fdns brite$

how to install libseccomp on mac?

**Comment by glitsj16** [comment]
> how to install libseccomp on mac?

[seccomp](https://en.wikipedia.org/wiki/Seccomp) is a Linux specific technology that requires the Linux kernel. You might be able to use Docker on OS X to get fdns (untested). Perhaps you could look into [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy), which has native support for OS X.
