### ISSUE TITLE
Mispelled Link

### ISSUE THREAD

**Issue by G-i-o** [netblue30/fdns#33]
Hello,

In your guides,  there's a spelling mistake in a link:

**git clone https://gihub.com/netblue30/fdns**

In the above link notice "gihub" instead of "github".

It's silly but drives you crazy if not spotted and all articles/guides on the Net seem to have picked the mispelled link.

Thank You!

**Comment by glitsj16** [comment]
Thanks for reporting, fixed now!

**Comment by G-i-o** [comment]
Perfect. Thank YOU. ;-)
