### ISSUE TITLE
Add --allow-local-doh option

### ISSUE THREAD

**Issue by sblighting** [netblue30/fdns#34]
From @rusty-snake in https://github.com/netblue30/fdns/pull/32

The ESNI implementation of firefox requires ATM that firefox resolves DNs itself suing its own DoH implementation. See the bugzilla ticket [1]. Some users might want this. Therefore it would be help full to have an --allow-local-doh options.

ESNI references:
about:config: network.security.esni.enabled
https://bugzilla.mozilla.org/show_bug.cgi?id=1500289 [1]
https://www.cloudflare.com/ssl/encrypted-sni (Test)
https://en.wikipedia.org/wiki/ESNI
https://blog.cloudflare.com/esni/

**Comment by rusty-snake** [comment]
Typo (from me), of curse we need only one option~s~.

> `--allow-local-doh` option**s**.

**Comment by startx2017** [comment]
Did some testing, looks fine.
