### ISSUE TITLE
whitelist for domain names

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/fdns#35]
A whitelist of allowed domain names would be very nice for use with single firejail sandboxes.

Example:
```
$ sudo fdns --proxy-addr=127.1.2.3 --wh-dn=mozilla.org --wh-dn=gmail.com
$ firejail --dns=127.1.2.3 thunderbird
```

Maybe it is better to put the whitelist in a file.

**Comment by startx2017** [comment]
Do you mean we should allow only the domains in the whitelist and drop all other? I would call it --whitelist:
`````
--whitelist=domain
--whitelist-file=filename
`````

**Comment by rusty-snake** [comment]
Yes, only whitelisted domain names are resolved.

**Comment by startx2017** [comment]
--whitelist is done, I'll look into --whitelist-filename

**Comment by netblue30** [comment]
I have enabled the code from @startx2017 - yes, it was an AppArmor problem, we were blacklisting the user file!
