### ISSUE TITLE
can't login DNS error for outlook.live.com

### ISSUE THREAD

**Issue by trytip** [netblue30/fdns#57]
1: using apt update on mint 19.3 will not work after fdns is loaded
2: outlook.live.com (microsoft outlook mail) dns error
3: github git command will not work after fdns is loaded

you can imagine how i bypassed verification code when the recovery email will not login just so that i can login to github for this issue 

using developer fdns version 0.9.65 i had to add 1.1.1.1 as fallback works for apt update but not outlook.live.com

**Comment by rusty-snake** [comment]
Can you give some more detailed STR. How/Where did you "load" fdns? What git command? What error do you see (from apt,git,fdns,...)?

-----

> 2: outlook.live.com (microsoft outlook mail) dns error

Looks like a false positive in trackers:

https://github.com/netblue30/fdns/blob/361868c5b9e9924df480e7e43d11c0c3e8548705/etc/trackers#L189

**Comment by trytip** [comment]
don't know what STR is. n where and how i load fdns according to the wiki https://github.com/netblue30/fdns/wiki/Download-and-Install

$ git clone https://github.com/netblue30/fdns
$ cd fdns
$ ./configure --prefix=/usr
$ make
$ sudo make install-strip
$ reboot
