### ISSUE TITLE
Update service ports for Quad9 DNS services

### ISSUE THREAD

**Issue by johnhtodd** [netblue30/fdns#61]
Hello -
  We're happy that the various service types for Quad9 are included in your list of available DoH servers.  However, the service port shown in the servers configuration file is 5053, which is an unsupported port that was "pre-standard".  It may be deprecated at some point in the future, or rate-limited now or in the future in ways that cause unexpected results for your user base.  We would suggest that you convert to port 443, which is the supported port number for DoH services.

**Comment by netblue30** [comment]
Fixed, thanks!
