### ISSUE TITLE
build from git master broken

### ISSUE THREAD

**Issue by glitsj16** [netblue30/fdns#63]
With https://github.com/netblue30/fdns/commit/3d616de78663ecf105a346dce7413dfbdb3edde2 I'm seeing ld errors and the build fails on Arch Linux.

```console
$ pacman -Q gcc libseccomp openssl
gcc 11.1.0-1
libseccomp 2.5.1-2
openssl 1.1.1.k-1
```

<details>
<summary> build log </summary>

` ` `
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for ranlib... ranlib
checking whether C compiler accepts -mindirect-branch=thunk... no
checking whether C compiler accepts -mretpoline... no
checking whether C compiler accepts -fstack-clash-protection... yes
checking whether C compiler accepts -fstack-protector-strong... yes
checking for main in -lpthread... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for pkg-config... pkg-config
checking whether compiling and linking against OpenSSL works... yes
OpenSSL library found
checking for main in -lseccomp... yes
checking seccomp.h usability... yes
checking seccomp.h presence... yes
checking for seccomp.h... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/common.mk
config.status: creating src/fdns/Makefile
config.status: creating src/nxdomain/Makefile
config.status: creating test/src/fdnstress/Makefile

Configuration options:
   prefix: /usr
   sysconfdir: /etc
   systemd directory: /usr/lib/systemd/system
   Spectre compiler patch: no
   apparmor: -DHAVE_APPARMOR
   seccomp: -DHAVE_SECCOMP
   EXTRA_LDFLAGS:
   EXTRA_CFLAGS:  -fstack-clash-protection -fstack-protector-strong
   fatal warnings:
   Gcov instrumentation:

make -C src/fdns
make -C test/src/fdnstress
make[1]: Entering directory '/build/fdns-git/src/fdns/src/fdns'
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c cache.c -o cache.o
make[1]: Entering directory '/build/fdns-git/src/fdns/test/src/fdnstress'
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c main.c -o main.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c dns.c -o dns.o
gcc  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -pie -Wl,-z,relro -Wl,-z,now -lpthread -lseccomp -o fdnstress main.o -lanl
make[1]: Leaving directory '/build/fdns-git/src/fdns/test/src/fdnstress'
make -C src/nxdomain
make[1]: Entering directory '/build/fdns-git/src/fdns/src/nxdomain'
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c nxdomain.c -o nxdomain.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c dnsdb.c -o dnsdb.o
gcc  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -pie -Wl,-z,relro -Wl,-z,now -lpthread -lseccomp -o nxdomain nxdomain.o
make[1]: Leaving directory '/build/fdns-git/src/fdns/src/nxdomain'
./mkman.sh 0.9.67 src/man/fdns.txt fdns.1
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c dot.c -o dot.o
./mkman.sh 0.9.67 src/man/nxdomain.txt nxdomain.1
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c filter.c -o filter.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c forwarder.c -o forwarder.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c frontend.c -o frontend.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c h11.c -o h11.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c h2.c -o h2.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c hpack_static.c -o hpack_static.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c huffman.c -o huffman.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c lint.c -o lint.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c log.c -o log.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c main.c -o main.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c net.c -o net.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c procs.c -o procs.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c resolver.c -o resolver.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c security.c -o security.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c server.c -o server.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c shmem.c -o shmem.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c ssl.c -o ssl.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c timetrace.c -o timetrace.o
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -ggdb  -O2 -DVERSION='"0.9.67"'    -DHAVE_SECCOMP -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/fdns"' -DLIBDIR='"/usr/lib"' -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -fstack-clash-protection -fstack-protector-strong  -c whitelist.c -o whitelist.o
gcc  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -pie -Wl,-z,relro -Wl,-z,now -lpthread -lseccomp -o fdns cache.o dns.o dnsdb.o dot.o filter.o forwarder.o frontend.o h11.o h2.o hpack_static.o huffman.o lint.o log.o main.o net.o procs.o resolver.o security.o server.o shmem.o ssl.o timetrace.o whitelist.o  -lssl -lcrypto -lrt
/usr/bin/ld: security.o: in function `trap_handler_resolver':
/build/fdns-git/src/fdns/src/fdns/security.c:89: undefined reference to `seccomp_syscall_resolve_num_arch'
/usr/bin/ld: security.o: in function `seccomp_resolver':
/build/fdns-git/src/fdns/src/fdns/security.c:131: undefined reference to `seccomp_arch_native'
/usr/bin/ld: /build/fdns-git/src/fdns/src/fdns/security.c:132: undefined reference to `seccomp_init'
/usr/bin/ld: /build/fdns-git/src/fdns/src/fdns/security.c:145: undefined reference to `seccomp_syscall_resolve_name'
/usr/bin/ld: /build/fdns-git/src/fdns/src/fdns/security.c:145: undefined reference to `seccomp_rule_add'
/usr/bin/ld: /build/fdns-git/src/fdns/src/fdns/security.c:150: undefined reference to `seccomp_load'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:9: fdns] Error 1
make[1]: Leaving directory '/build/fdns-git/src/fdns/src/fdns'
make: *** [Makefile:23: src/fdns] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

` ` `

</details>

**Comment by netblue30** [comment]
Could be something with the newer version of the linker (ldd)? Works fine here on Debian 10.

Try this: in src/fdns/Makefile.in on line 9 add a -lseccomp after -lrt something like this:
`````
	$(CC)  $(LDFLAGS) -o $@ $(OBJS)  -lssl -lcrypto -lrt -lseccomp $(LIBS) $(EXTRA_LDFLAGS)
`````

I think -lseccomp should have been added to $(LIBS) not to $(LDFLAGS).

**Comment by glitsj16** [comment]
> I think -lseccomp should have been added to $(LIBS) not to $(LDFLAGS).

Spot on! This fixes the build.
