### ISSUE TITLE
Fedora: "Failed to enable unit: Unit file fdns.service does not exist."

### ISSUE THREAD

**Issue by Futureknows** [netblue30/fdns#68]
What is the simplest way to automatically run FDNS at boot in Fedora?
The [instructions](https://github.com/netblue30/fdns/wiki/Starting-the-Proxy) don't work on F34 here:

```
On systemd systems, you can start FDNS when the system is starting by enabling its unit.
# systemctl enable fdns.service
Failed to enable unit: Unit file fdns.service does not exist.
```

**Comment by rusty-snake** [comment]
Well, you need to add fdns.service to systemd. You can not enable a unit that systemd isn't aware of. How did you installed fdns?

**Comment by rusty-snake** [comment]
If `/etc/systemd/system/fdns.service` or `/usr/lib/systemd/system/fdns.service` exist when you execute `systemctl enable fdns.service`, you need to tell systemd first that it exists. Either restart your system run execute `systemctl daemon-reload`.

**Comment by Futureknows** [comment]
rpmbuild wasn't in the Fedora 34 repo so I compiled from git.
I presume that's the problem, I'll get rpmbuild and follow the Fedora
script.
Thanks

**Comment by rusty-snake** [comment]
> rpmbuild wasn't in the Fedora 34 repo so I compiled from git

```
sudo dnf install rpm-build
```
