### ISSUE TITLE
[Q] Default for AAAA queries

### ISSUE THREAD

**Issue by rusty-snake** [netblue30/fdns#8]
manpage:
> **--allow-all-queries**
Allow all DNS query types; by default only A and AAA are allowed.

> **--ipv6**
Allow AAAA requests.

So what is the default for `AAAA` queries?

**Comment by netblue30** [comment]
Thanks, fixed in https://github.com/netblue30/fdns/commit/6f1a8f33235031f18547429d1877d8419fd227cb
