### ISSUE TITLE
Latest coinblocker list update contains invalid entrees

### ISSUE THREAD

**Issue by glitsj16** [netblue30/fdns#82]
The latest [coinblocker](https://raw.githubusercontent.com/netblue30/fdns/master/etc/coinblocker) list update from https://github.com/netblue30/fdns/commit/b2b54624a0b842eb895834d31fade8d8e370db3b contains a few invalid entrees:

```sh
$ grep "\.\." coinblocker
127.0.0.1 fgdfg5e5sd..ydns.eufgeydns.eufge9vbrzwt.bid
127.0.0.1 nonublicnode.ydnoname..ydnoname.nodes.cluster.bitfex.tnonametrade.com
127.0.0.1 mynetwork..webhop.mmynebhop.mmynewmining.com
```

Those `double dots` need replacing by a `single dot` IMO.

Note: I couldn't find these in the referenced sources:

- https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts
- https://raw.githubusercontent.com/blocklistproject/Lists/master/crypto.txt

A simple `sed -i -e "s/\.\./\./g" coinblocker` did the trick.

**Comment by netblue30** [comment]
fixed, thanks!
