### ISSUE TITLE
Removal of blocklist

### ISSUE THREAD

**Issue by Amir1453** [netblue30/fdns#84]
Hello, why exactly was blacklisting domains removed recently? I understand the need to cleanup the code but blacklisting seems like an essential feature. Was it perhaps replaced by something else?

**Comment by netblue30** [comment]
I've been cleaning up some of the rarely used features. If you are on the latest released version, add a hosts file in /etc/fdns/hosts.

I've just added a default one in the latest commit here: https://github.com/netblue30/fdns/blob/master/etc/hosts. It should work in the latest version.

**Comment by Amir1453** [comment]
Is there anyway to specify host files for separate fdns instances?

**Comment by netblue30** [comment]
No problem, I brought it back under --blocklist-file=... name. Also, you can set up to 8 additional files for each independent fdns instance.

**Comment by Amir1453** [comment]
Thank you for the quick resolution. I am closing this issue as I believe it has been resolved. Thanks again for the practical software.
